repos:
  - repo: local
    hooks:
      - id: docker-isort
        name: isort
        language: system
        require_serial: true
        entry: >
          ./simple_backend/_dev/.pre-commit/docker-pre-commit.sh
          python3 -m isort --profile black --filter-files --combine-as --src simple_backend
        files: \.pyi?$
  - repo: local
    hooks:
      - id: docker-black
        name: black
        language: system
        require_serial: true
        entry: >
          ./simple_backend/_dev/.pre-commit/docker-pre-commit.sh
          python3 -m black --target-version py312 --line-length 100
        files: \.pyi?$
